In [17]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model,preprocessing
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier

In [18]:
from google.colab import files
uploaded = files.upload()

Saving car.data to car (1).data


In [19]:
import io
data = pd.read_csv(io.BytesIO(uploaded['car.data']))
print(data.head())

  buying  maint door persons lug_boot safety  class
0  vhigh  vhigh    2       2    small    low  unacc
1  vhigh  vhigh    2       2    small    med  unacc
2  vhigh  vhigh    2       2    small   high  unacc
3  vhigh  vhigh    2       2      med    low  unacc
4  vhigh  vhigh    2       2      med    med  unacc


In [20]:
l = preprocessing.LabelEncoder()

In [21]:
buying = l.fit_transform(list(data['buying']))
maint = l.fit_transform(list(data['maint']))
door = l.fit_transform(list(data['door']))
persons = l.fit_transform(list(data['persons']))
lug_boot = l.fit_transform(list(data['lug_boot']))
safety = l.fit_transform(list(data['safety']))
cls = l.fit_transform(list(data['class']))

In [22]:
X = list(zip(buying,maint,door,persons,lug_boot,safety))
Y = list(cls)

In [23]:
x_train,x_test,y_train,y_test = sklearn.model_selection.train_test_split(X,Y,test_size=0.1)

In [24]:
print(x_train)
print(y_test)

[(0, 2, 1, 0, 0, 1), (3, 2, 0, 2, 1, 0), (1, 0, 0, 2, 1, 1), (0, 0, 0, 0, 1, 1), (0, 3, 3, 2, 2, 2), (3, 1, 3, 2, 1, 0), (0, 0, 1, 2, 1, 0), (0, 2, 2, 1, 1, 1), (2, 1, 2, 0, 2, 0), (3, 0, 0, 0, 1, 0), (2, 0, 1, 1, 2, 2), (2, 0, 3, 1, 0, 1), (1, 3, 3, 1, 1, 1), (0, 3, 0, 0, 1, 2), (2, 1, 2, 0, 1, 2), (3, 0, 3, 0, 0, 0), (0, 2, 2, 0, 1, 1), (3, 2, 3, 1, 2, 2), (3, 3, 3, 1, 1, 0), (3, 0, 3, 2, 0, 2), (1, 1, 0, 2, 2, 1), (3, 0, 3, 2, 1, 0), (0, 1, 2, 1, 0, 1), (1, 0, 1, 1, 1, 2), (0, 1, 0, 1, 2, 1), (3, 2, 1, 2, 0, 2), (2, 3, 0, 0, 2, 2), (2, 3, 2, 1, 1, 1), (1, 2, 3, 1, 0, 0), (3, 1, 0, 0, 1, 1), (0, 0, 0, 2, 2, 2), (1, 3, 3, 1, 1, 0), (0, 1, 1, 1, 2, 1), (0, 2, 3, 0, 1, 1), (2, 1, 3, 2, 2, 0), (2, 3, 3, 1, 2, 2), (0, 2, 3, 0, 2, 1), (2, 3, 3, 1, 2, 0), (2, 2, 3, 1, 1, 2), (3, 1, 1, 2, 0, 2), (0, 0, 0, 0, 0, 0), (0, 1, 2, 1, 1, 2), (2, 1, 1, 0, 0, 1), (2, 3, 0, 0, 0, 2), (2, 2, 3, 0, 2, 1), (1, 1, 0, 0, 1, 0), (2, 2, 2, 0, 0, 2), (3, 0, 2, 0, 1, 0), (0, 3, 2, 1, 2, 2), (0, 1, 1, 0, 2, 2),

In [25]:
model = KNeighborsClassifier(n_neighbors=5)

In [26]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
acc = model.score(x_test,y_test)
print(acc)

0.9017341040462428


In [28]:
predicted = model.predict(x_test)

In [31]:
names = ["unacc","acc","good","vgood"]
for x in range(len(predicted)):
  print("Predicted Values : ", names[predicted[x]], "Input Data Set:", x_test[x],"Actual Values :", names[y_test[x]])
  n = model.kneighbors([x_test[x]],5,True)
  print(n)

Predicted Values :  good Input Data Set: (0, 2, 0, 2, 2, 2) Actual Values : good
(array([[1., 1., 1., 1., 1.]]), array([[1127,  762,  906, 1117,  711]]))
Predicted Values :  good Input Data Set: (1, 3, 2, 0, 0, 0) Actual Values : good
(array([[1., 1., 1., 1., 1.]]), array([[1065, 1428, 1133,  119,  899]]))
Predicted Values :  good Input Data Set: (3, 1, 1, 0, 2, 0) Actual Values : good
(array([[1., 1., 1., 1., 1.]]), array([[1423,  829, 1472,  135, 1119]]))
Predicted Values :  good Input Data Set: (2, 2, 2, 2, 1, 1) Actual Values : good
(array([[1., 1., 1., 1., 1.]]), array([[ 270, 1528,  577,  375,  916]]))
Predicted Values :  good Input Data Set: (3, 1, 1, 1, 0, 1) Actual Values : good
(array([[1., 1., 1., 1., 1.]]), array([[ 382, 1302,  799,  790,  302]]))
Predicted Values :  unacc Input Data Set: (3, 1, 2, 1, 0, 2) Actual Values : unacc
(array([[1., 1., 1., 1., 1.]]), array([[820, 791, 628, 382, 295]]))
Predicted Values :  good Input Data Set: (3, 1, 3, 2, 2, 2) Actual Values : goo